# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['BASE_URL']

# Cell
import requests
import warnings


BASE_URL = "https://developer.nrel.gov"


class _GetPostRequest:
    """
    """

    QUERY_URL = ""

    def __init__(self):

        self._params = {}

    def _get(self):
        """Process the get request"""
        resp = requests.get(BASE_URL + self.QUERY_URL, params=self._params)
        content = resp.json()

        # if any warnings are encountered, bring them up to the user
        if content.get("warnings"):
            warnings.warn(message=str(content["warnings"]), category=UserWarning)
        return content
