# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['get_request', 'BASE_URL']

# Cell
import requests
import warnings


BASE_URL = "https://developer.nrel.gov"


def get_request(query_url, params):
    """Process the get request and returns the complete response"""

    resp = requests.get(BASE_URL + query_url, params=params)

    content = resp.json()

    # if any warnings are encountered, bring them up to the user
    if content.get("warnings"):
        warnings.warn(message=str(content["warnings"]), category=UserWarning)

    return resp