# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BASE_URL": "00_core.ipynb",
         "SolarResourceData": "01_solar.resource_data.ipynb",
         "SolarDatasetQuery": "02_solar.dataset_query.ipynb",
         "PVWattsV6": "03_solar.pvwatts_v6.ipynb"}

modules = ["_core.py",
           "solar/resource_data.py",
           "solar/dataset_query.py",
           "solar/pvwatts_v6.py"]

doc_url = "https://sarthakjariwala.github.io/nrel_dev_api/"

git_url = "https://github.com/sarthakjariwala/nrel_dev_api/tree/master/"

def custom_doc_links(name): return None
