# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SolarResourceData": "00_solar.ipynb"}

modules = ["solar.py"]

doc_url = "https://sarthakjariwala.github.io/nrel_dev_api/"

git_url = "https://github.com/sarthakjariwala/nrel_dev_api/tree/master/"

def custom_doc_links(name): return None
