# AUTOGENERATED! DO NOT EDIT! File to edit: 01_solar.resource_data.ipynb (unless otherwise specified).

__all__ = ['SolarResourceData']

# Cell
from ..core import _GetPostRequest

# TODO - add attributes in docstring, add checks for data inputs
class SolarResourceData(_GetPostRequest):
    """Returns various types of solar data for a location as a dictionary.
    The service from NREL currently returns data for
    average Direct Normal Irradiance, average Global Horizontal Irradiance,
    and average Tilt at Latitude.

    Attributes:

        api_key: NREL Developer API key (https://developer.nrel.gov/signup/).
        lat: Latitude of the location.
        lon: Longitude of the location.
        address: Address of the location to use. Required if lat/lon not specified.
    """

    QUERY_URL = "/api/solar/solar_resource/v1.json"

    def __init__(self, api_key, lat=None, lon=None, address=None):

        super().__init__()

        self._params.update({"api_key": api_key})

        # if address is not specified latitude and longitude must be specified
        if not address:
            self._params.update({"lat" : lat, "lon" : lon})
        else:
            self._params.update({"address": address})

        # complete response as a dict
        self.response = self._get()

        # only the outputs
        self.outputs = self.response["outputs"]

        # get the inputs provided
        self.inputs = self.response["inputs"]