baseurl: /nrel_dev_api/
collections:
  tooltips:
    output: false
company_name: Sarthak Jariwala
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: Python API for NREL (National Renewable Energy Lab) developer API
exclude:
- vendor
google_analytics: null
google_search: null
highlighter: rouge
host: 127.0.0.1
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
output: web
plugins:
- jekyll-remote-theme
port: 4000
remote_theme: fastai/nbdev-jekyll-theme
repository: sarthakjariwala/nrel_dev_api
sidebars:
- home_sidebar
site_title: nrel_dev_api
topnav_title: nrel_dev_api
use_math: true
